# Generated by Django 4.2.30 on 2026-07-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_title', models.CharField(max_length=100)),
                ('wpm', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('date_played', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
