# Generated by Django 4.2.30 on 2026-07-16 04:22

from django.db import migrations, models
import typingApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('typingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=typingApp.models.generate_room_code, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
